### ISSUE TITLE
沒有不分區立委的電話

### ISSUE THREAD

**Issue by 13579chen** [7holidays/7holidays.github.io#4]
這次的勞基法修法不分區立委也大力護航，怎麼沒有放不分區立委的電話呢？

**Comment by yurenju** [comment]
@13579chen 因為資料結構的關係這個有一點點麻煩，可能會稍微晚一點弄

**Comment by yurenju** [comment]
先講一下做法看有沒有人可以幫忙解，這要做的事：
1. 修正 raw/process.js: 因為目前是切前面三個字把像是 `臺北市` 這樣的字切出來，所以可能要排除不分區立委
2. 在頁面上新增 `不分區` 到 `cities` 資料結構裡面，再把資訊頁出來。

**Comment by yurenju** [comment]
fixed on commit bf48d64775e97bf3cee6c45d142d9865e6934fb8
